name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Up Dependencies
      run: sudo apt-get install -y gdb
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
    - name: Run Client and Server tests
      run: |
        export GDB_COMMAND_TIMEOUT=3
        cargo build --bin test_app
        cargo run --bin gdb_client -- --log-level debug -e target/debug/test_app
